name: LaTeX Compile/Build
on: 
    workflow_dispatch:
        inputs:
            title:
                description: "Title of document"
                default: "main"
                type: string
                required: false

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Rename file 
        run:
            mv main.pdf ${{ inputs.title }}.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: ${{ inputs.title }}.pdf